// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwcequzybbvggxrdtymf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13Y2VxdXp5YmJ2Z2d4cmR0eW1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1OTQwMzMsImV4cCI6MjA3NzE3MDAzM30.byYUCGC3A9kukOVGZZAn3QWnb9SE5_dffmegkIirmVM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});